springdoc:
   api-docs.path: /api-docs
   swagger-ui.path: /swagger-ui.html
spring:
   jmx.enabled: true
   application.name: workspace-manager
   boot.admin.client:
      enabled: true
      url: http://localhost:8089
      instance:
         service-path: /
         prefer-ip: false
logging:
   file:
      name: ./logs/${spring.application.name}.log
   logback.rollingpolicy:
      max-file-size: 10MB
      max-history: 2
      total-size-cap: 30MB
      clean-history-on-start: true
      file-name-pattern: ./logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
   level:
      org.apache.kafka.clients: info
      org.camunda.bpm.client: info
management:
   metrics:
      export:
         atlas:
            enabled: false
            step: 5s
            uri: http://localhost:7101/api/v1/publish
         elastic:
            enabled: false
            step: 5s
            host: http://192.168.56.4:9200
            index: metrics-${spring.application.name}
            indexDateFormat: yyyy-MM-dd
   endpoints:
      health.binders.enabled: true
      enabled-by-default: true
      web:
         exposure.include: '*'
         cors:
            allowed-origins: '*'
            allowed-methods: GET,POST,PUT
      jmx.exposure.include: '*'
   endpoint:
      health.show-details: always

# CLEAN THE OBSOLETED FILES
file-management:
   reporter:
      enabled: true
      schedule: '* * 0/15 * *'
      rules[size]:
         larger-than: 5MB
      rules[obsolete]:
         older-than: 50h
   actions[size]:
      action: DELETE
   actions[obsolete]:
      action: LOG
      